version: '3.2'
services:
  geth-goerli:
    image: ethereum/client-go:v1.10.2
    ports:
      - 8545:8545
      - 8546:8546
      - 35555:30303
    volumes:
      - goerli-1:/root/.ethereum
    restart: always
    command:
      - '--goerli'
      - '--http'
      - '--http.corsdomain=*'
      - '--http.vhosts=*'
      - '--http.addr=0.0.0.0'
      - '--cache=2048'
      - '--ws'
      - '--ws.addr=0.0.0.0'
      - '--light.nosyncserve'
  
volumes:
  goerli-1: